# Generated by Django 5.0 on 2024-01-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_email_member_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
