# Generated by Django 5.0 on 2024-01-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pic',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
