# Generated by Django 5.0 on 2024-01-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_sub_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
