# Generated by Django 5.0 on 2024-01-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_sub_sub_refno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_amount',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_refno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='sub_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='sub_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
